export enum Tech {
  NODEJS = "nodejs",
  JS = "javascript",
  TS = "typescript",
  HTML = "html",
  CSS = "css",
  PYTHON = "python",
  SWIFT = "swift",
  GATSBY = "gatsby",
  REACT = "react",
  RUST = "rust",
  C = "c",
  BASH = "bash",
  DOCKER = "docker",
  FIREBASE = "firebase",
  EXPRESS = "express",
  JAVA = "java",
  MONGODB = "mongodb",
  NEXT = "next",
  R = "r",
  VUE = "vue",
  SPRING = "spring",
  ELECTRON = "electron",
  MYSQL = "mysql",
}
